#
# The IP address for Cloudera Manager machine is 192.168.33.10 !!!
#
Vagrant::Config.run do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "lucid64"

  # Boot with a GUI so you can see the screen. (Default is headless)
  #config.vm.boot_mode = :gui

  # hack to avoid 'vagrant up'  hang
  config.vm.customize ["modifyvm", :id, "--rtcuseutc", "on"]
  # increase available memory
  config.vm.customize ["modifyvm", :id, "--memory", 2048]

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

  #config.vm.provision :shell, :path => "install-cm-and-cdh.sh"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.10"

end
